#!/usr/bin/env bash

set -euo pipefail

# Run each tests/*.test.ts file separately to avoid account state persisting between tests
for file in `ls tests/*.test.ts`
do
    # convert file-name to FILE_NAME
    filename=$(basename -- "$file")
    filename="${filename%.test.*}"
    env_flag="$(tr '[:lower:]' '[:upper:]' <<< ${filename//-/_})"

    env $env_flag=1 bash -c 'anchor test --skip-build'

    # kill solana validator if still running to avoid port already in use error
    if pgrep solana-test-validator; then pkill solana-test-validator; fi
done