/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  GovernedContract,
  GovernedContractInterface,
} from "../../Governance.t.sol/GovernedContract";

const _abi = [
  {
    type: "function",
    name: "governanceRevert",
    inputs: [],
    outputs: [],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "governanceStuff",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "governanceStuffCalled",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "bool",
        internalType: "bool",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "owner",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "address",
        internalType: "address",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "renounceOwnership",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "transferOwnership",
    inputs: [
      {
        name: "newOwner",
        type: "address",
        internalType: "address",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "event",
    name: "OwnershipTransferred",
    inputs: [
      {
        name: "previousOwner",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "newOwner",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "error",
    name: "RandomError",
    inputs: [],
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b5061001a3361001f565b61006f565b600080546001600160a01b038381166001600160a01b0319831681178455604051919092169283917f8be0079c531659141344cd1fd0a4f28419497f9722a3daafe3b4186f6b6457e09190a35050565b6102b88061007e6000396000f3fe608060405234801561001057600080fd5b50600436106100625760003560e01c80635aaa10fb14610067578063715018a61461009057806371cd25f91461009a5780638da5cb5b146100a2578063e46a3942146100bd578063f2fde38b146100c5575b600080fd5b60005461007b90600160a01b900460ff1681565b60405190151581526020015b60405180910390f35b6100986100d8565b005b6100986100ec565b6000546040516001600160a01b039091168152602001610087565b610098610109565b6100986100d3366004610252565b61012a565b6100e06101a8565b6100ea6000610202565b565b6100f46101a8565b6000805460ff60a01b1916600160a01b179055565b6101116101a8565b60405163224fd24160e11b815260040160405180910390fd5b6101326101a8565b6001600160a01b03811661019c5760405162461bcd60e51b815260206004820152602660248201527f4f776e61626c653a206e6577206f776e657220697320746865207a65726f206160448201526564647265737360d01b60648201526084015b60405180910390fd5b6101a581610202565b50565b6000546001600160a01b031633146100ea5760405162461bcd60e51b815260206004820181905260248201527f4f776e61626c653a2063616c6c6572206973206e6f7420746865206f776e65726044820152606401610193565b600080546001600160a01b038381166001600160a01b0319831681178455604051919092169283917f8be0079c531659141344cd1fd0a4f28419497f9722a3daafe3b4186f6b6457e09190a35050565b60006020828403121561026457600080fd5b81356001600160a01b038116811461027b57600080fd5b939250505056fea2646970667358221220d3cd68d8c514762feff8b30e8426e0184111240b8b9a475b19c0f4407d54b46764736f6c63430008130033";

type GovernedContractConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: GovernedContractConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class GovernedContract__factory extends ContractFactory {
  constructor(...args: GovernedContractConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: string }
  ): Promise<GovernedContract> {
    return super.deploy(overrides || {}) as Promise<GovernedContract>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: string }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): GovernedContract {
    return super.attach(address) as GovernedContract;
  }
  override connect(signer: Signer): GovernedContract__factory {
    return super.connect(signer) as GovernedContract__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): GovernedContractInterface {
    return new utils.Interface(_abi) as GovernedContractInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): GovernedContract {
    return new Contract(address, _abi, signerOrProvider) as GovernedContract;
  }
}
