/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { GovernanceTest__factory } from "./GovernanceTest__factory";
export { GovernedContract__factory } from "./GovernedContract__factory";
