/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../common";

export type NormalizedAmountStruct = {
  amount: BigNumberish;
  decimals: BigNumberish;
};

export type NormalizedAmountStructOutput = [BigNumber, number] & {
  amount: BigNumber;
  decimals: number;
};

export interface NormalizedAmountLibInterface extends utils.Interface {
  functions: {
    "min((uint64,uint8),(uint64,uint8))": FunctionFragment;
  };

  getFunction(nameOrSignatureOrTopic: "min"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "min",
    values: [NormalizedAmountStruct, NormalizedAmountStruct]
  ): string;

  decodeFunctionResult(functionFragment: "min", data: BytesLike): Result;

  events: {};
}

export interface NormalizedAmountLib extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: NormalizedAmountLibInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    min(
      a: NormalizedAmountStruct,
      b: NormalizedAmountStruct,
      overrides?: CallOverrides
    ): Promise<[NormalizedAmountStructOutput]>;
  };

  min(
    a: NormalizedAmountStruct,
    b: NormalizedAmountStruct,
    overrides?: CallOverrides
  ): Promise<NormalizedAmountStructOutput>;

  callStatic: {
    min(
      a: NormalizedAmountStruct,
      b: NormalizedAmountStruct,
      overrides?: CallOverrides
    ): Promise<NormalizedAmountStructOutput>;
  };

  filters: {};

  estimateGas: {
    min(
      a: NormalizedAmountStruct,
      b: NormalizedAmountStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    min(
      a: NormalizedAmountStruct,
      b: NormalizedAmountStruct,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
