name: EVM CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: forge test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        run: |
          make test-push0
        id: build

      - name: Run Forge tests
        run: |
          make test-evm
        id: test

      - name: Run Forge fmt
        run: |
          make check-format
        id: check
    
    name: echidna
    runs-on: ubuntu-latest
    steps:
      steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        run: |
          make test-push0
        id: build

      - uses: crytic/echidna-action@v2
        with:
          files: ./evm/echidna
          config: ./evm/echidna.yaml
          crytic-args: --ignore-compile