name: SDK CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

env:
  FOUNDRY_PROFILE: prod

jobs:
  check:
    strategy:
      fail-fast: true

    name: typechain match
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        run: |
          cd evm
          forge build
        id: build

      - name: Run Typechain
        run: |
          cd ci_tests
          npm ci
          npm run gen-evm-bindings
        id: generate

      - name: Diff
        run: |
          git diff --name-only --exit-code && echo "✅ Generated typechain matches committed typechain" || (echo "❌ Generated typechain differs from committed typechain, run \`make gen-evm-bindings\` and commit the result" >&2 && exit 1)
        id: check
